project_id = "fwhqtzkkvnjkazhaficj"

[functions.get-signed-valuation-url]
verify_jwt = true

[functions.sync-from-brevo]
verify_jwt = true

[functions.sync-to-brevo]
verify_jwt = true

[functions.extract-data-from-image]
verify_jwt = true

[functions.sync-leads-to-crm]
verify_jwt = false
