project_id = "fwhqtzkkvnjkazhaficj"

[functions.get-signed-valuation-url]
verify_jwt = true

[functions.sync-from-brevo]
verify_jwt = true

[functions.sync-to-brevo]
verify_jwt = true

[functions.extract-data-from-image]
verify_jwt = true

[functions.sync-leads-to-crm]
verify_jwt = false

[functions.sync-operations-to-crm]
verify_jwt = false

[functions.firecrawl-scrape]
verify_jwt = true

[functions.enrich-company]
verify_jwt = true

[functions.sync-deals-from-brevo]
verify_jwt = true

[functions.extract-financial-statements]
verify_jwt = true
